# Generated by Django 3.1.5 on 2021-05-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210427_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bio',
            field=models.TextField(default='no bio...', max_length=300),
        ),
        migrations.AddField(
            model_name='customer',
            name='dob',
            field=models.DateField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='flavor',
            field=models.CharField(choices=[('Chocolate', 'Chocolate'), ('Snickerdoodle', 'Snickerdoodle'), ('Cookies & Cream', 'Cookies & Cream'), ('Strawberry', 'Strawberry'), ('Vanilla', 'Vanilla'), ('Fruits', 'Fruits')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacture',
            field=models.CharField(choices=[('Kabs', 'Kabs'), ('First Nutrition', 'First Nutrition'), ('Go Tamreen', 'Go Tamreen'), ('Supplements Mall', 'Supplements Mall'), ('Protinak', 'Protinak')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ptype',
            field=models.CharField(choices=[('Bars', 'Bars'), ('Drinks', 'Drinks'), ('Powder', 'Powder'), ('Tablets & Capsules', 'Tablets & Capsules')], max_length=200, null=True),
        ),
    ]
