# Generated by Django 3.1.5 on 2021-05-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210504_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='food',
        ),
        migrations.AddField(
            model_name='product',
            name='food_flavor',
            field=models.CharField(choices=[('20g', '20g'), ('50g', '50g'), ('80g', '80g'), ('100g', '100g'), ('150g', '150g'), ('200g', '200g')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='food_manufacture',
            field=models.CharField(choices=[('Muscle Kitchen', 'Muscle Kitchen'), ('Thefitbar', 'Thefitbar'), ('Fit Food Factory', 'Fit Food Factory'), ('Calories Healthy Food Resturant', 'Calories Healthy Food Resturant'), ("OJ's - Super Fast Salads", "OJ's - Super Fast Salads")], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='food_type',
            field=models.CharField(choices=[('Salad', 'Salad'), ('Drinks', 'Drinks'), ('Protin', 'Protin'), ('Carbs', 'Carbs')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
